routes:
    home:
        method: GET
        path: /
        defaults:
            action: home
    catchall:
        allows: [POST, GET]
        path: "{/controller,action}"
        wildcard: args
defaults:
    namespace: UserInterface\Controller
    action: index
    controller: pages